* Reading Smalltalk Best Practice Patters

** next reading
Patterns
file:~/Programming/Pyrulis/Smalltalk/reading-smalltalk-best-practice-patterns.org::100

** interesting parts
[[*Organisation][Organisation]]

** book

*** Index
pdf:/home/jacek/Documents/Manuals/Smalltalk/Smalltalk-Best-Practice-Patterns-Kent-Beck.pdf#2

*** Preface
pdf:/home/jacek/Documents/Manuals/Smalltalk/Smalltalk-Best-Practice-Patterns-Kent-Beck.pdf#5

It is a style guide. Tries to penetrate beneath the surface to understand why the rules work.

Covers naming, breaking logic into smaller components, and communicating clearly
through the code.

The advice is broken into 89 patterns.

Naming trade offs: include lot of information in the name, keep the name short, avoid
redundant information, reason for existence, type
Name it after the role it plays
What can be inferred from context?

*** Introduction
pdf:/home/jacek/Documents/Manuals/Smalltalk/Smalltalk-Best-Practice-Patterns-Kent-Beck.pdf#8

*** Coding
pdf:/home/jacek/Documents/Manuals/Smalltalk/Smalltalk-Best-Practice-Patterns-Kent-Beck.pdf#9

#+begin_quote
In this model, coding isn’t the poor handmaiden of design or analysis. Coding is where your fuzzy
comfortable ideas awaken in the harsh dawn of reality. It is where you learn what your computer
can do. If you stop coding, you stop learning.
#+end_quote

**** Talking Programs
pdf:/home/jacek/Documents/Manuals/Smalltalk/Smalltalk-Best-Practice-Patterns-Kent-Beck.pdf#9

If program out of sudden gets difficult, it's talking to you. It is trying to
tell you that something important is missing.

Many patterns will guide you when the program talks to you. And you have to
listen before you can react.

**** Good Software

**** Style
pdf:/home/jacek/Documents/Manuals/Smalltalk/Smalltalk-Best-Practice-Patterns-Kent-Beck.pdf#13

You recognise it when you see it

Once and only once
Lots of little pieces
Replaceable objects
Moving objects to new contexts
Rates of change should match

**** What's Missing

**** Organisation
pdf:/home/jacek/Documents/Manuals/Smalltalk/Smalltalk-Best-Practice-Patterns-Kent-Beck.pdf#15


***** Patterns
The philosophy behind patterns.

***** Behavior
Patterns for methods and messages. The problems you can solve by creating a new
method. You will also find method patterns scattered throughout the remainder of the patterns,
if a particular kind of method (like accessors) is tied to another pattern. The quick reference
guide gathers all the method patterns together for easy reference.

***** State
Patterns for using instance and temporary variables. You will find a discussion of the
pros and cons of using accessor methods and direct variable access.

***** Collections
The major collection classes and messages in the form of patterns. You will also
find common tricks using collection

***** Classes
A brief introduction to how to use classes, since most of the topics regarding class
creation are outside the scope of this book.

***** Formatting
My rules of code formatting, cast as patterns.

***** Development Example
An example of developing objects with explicit reference to the
patterns as they apply.

**** Adoption
Read the book quickly in one go, and then use it as a reference when you program.

*** Patterns
pdf:/home/jacek/Documents/Manuals/Smalltalk/Smalltalk-Best-Practice-Patterns-Kent-Beck.pdf#17

#+begin_quote
Each pattern records a solution to a single recurring problem, including how to
recognize the presence of the problem and how to generate the solution so that
it fits the context. Patterns lead naturally one to the other, forming a kind of
flexible fabric of decisions
#+end_quote

**** WHY PATTERNS WORK
pdf:/home/jacek/Documents/Manuals/Smalltalk/Smalltalk-Best-Practice-Patterns-Kent-Beck.pdf#18
**** ROLE OF PATTERNS
pdf:/home/jacek/Documents/Manuals/Smalltalk/Smalltalk-Best-Practice-Patterns-Kent-Beck.pdf#20
***** Reading
pdf:/home/jacek/Documents/Manuals/Smalltalk/Smalltalk-Best-Practice-Patterns-Kent-Beck.pdf#20
***** Development
pdf:/home/jacek/Documents/Manuals/Smalltalk/Smalltalk-Best-Practice-Patterns-Kent-Beck.pdf#20
***** Review
pdf:/home/jacek/Documents/Manuals/Smalltalk/Smalltalk-Best-Practice-Patterns-Kent-Beck.pdf#20
***** Documentation
pdf:/home/jacek/Documents/Manuals/Smalltalk/Smalltalk-Best-Practice-Patterns-Kent-Beck.pdf#20
***** Clean Up
pdf:/home/jacek/Documents/Manuals/Smalltalk/Smalltalk-Best-Practice-Patterns-Kent-Beck.pdf#20
**** FORMAT
pdf:/home/jacek/Documents/Manuals/Smalltalk/Smalltalk-Best-Practice-Patterns-Kent-Beck.pdf#21

*** Behaviour
pdf:/home/jacek/Documents/Manuals/Smalltalk/Smalltalk-Best-Practice-Patterns-Kent-Beck.pdf#22

*** Collections
pdf:/home/jacek/Documents/Manuals/Smalltalk/Smalltalk-Best-Practice-Patterns-Kent-Beck.pdf#84

*** Classes
pdf:/home/jacek/Documents/Manuals/Smalltalk/Smalltalk-Best-Practice-Patterns-Kent-Beck.pdf#122

*** Formatting
pdf:/home/jacek/Documents/Manuals/Smalltalk/Smalltalk-Best-Practice-Patterns-Kent-Beck.pdf#126

*** Development Example
pdf:/home/jacek/Documents/Manuals/Smalltalk/Smalltalk-Best-Practice-Patterns-Kent-Beck.pdf#140
