/*
 * This file has been automatically generated by cffi-grovel.
 * Do not edit it by hand.
 */

#include </usr/include/gtk-3.0/gtk/gtk.h>

#include <grovel/common.h>

int main(int argc, char**argv) {
  int autotype_tmp;
  FILE *output = argc > 1 ? fopen(argv[1], "w") : stdout;
  fprintf(output, ";;;; This file has been automatically generated by "
                  "cffi-grovel.\n;;;; Do not edit it by hand.\n\n");

  if  (output != stdout)
    fclose(output);
  return 0;
}
