* Pharo

** pharo wiki
https://github.com/pharo-open-documentation/pharo-wiki

*** for beginners
https://github.com/pharo-open-documentation/pharo-wiki/blob/master/General/MustKnowForBeginners.md

** syntax
https://files.pharo.org/media/pharoCheatSheet.pdf

** Progress

Use Paro Launcher to rename latest 11-64 bit pharo as counter.

Launch a Pharo named counter in the Launcher

Close welcome window

Menu Browse System browser Ctrl o b - note tool-tip is wrong in Pharo 11

*** Package
Right click top leftmost area and select option New package
Enter the package name Jacpac

*** Class
In the top left window select Jacpac
New class tab will show in bottom part with the class stub
edit Object subclass: #MyClass and name it #JacClass
Right click and select Accept
top second left pane will show new JacClass

Right click on JacClass and select Jump to test class
that will generate package Jacpac-Tests and class JacClassTest
on third from left pane instance side will show
Right clicking instance side will show menu
Click on New protocol
A window will appear where I searched and selected counting
that has added new item counting to third from left pane
The bottom pane tab Inst. side method will have code skeleton

*** Test Methods
Edit the bottom pane code skeleton tab Inst. side method to look like
#+begin_example
testCreatingJacClass
  "A test that will check if the creation of an object JacClass is done properly"
  |tmp|
  tmp := JacClass new.
  self deny: (tmp = nil)
#+end_example
Right click bottom pane and Accept
That will show new method in fourth from left pane

On bottom pane select Inst. side method tab
Edit the code to look like
#+begin_example
testIncrementing
  "A test that will check if method increment is working properly.
    Test value 5. Expected result 6."
  |counter|
  counter := JacClass new.
  counter value: 5.
  counter increment.
  self assert: (counter value = 6)
#+end_example
Right click on the block and Accept
A new method will show in fourth from left pane

On bottom pane select Inst. side method tab
Edit the code to for Decrementing value test
https://github.com/pharo-open-documentation/pharo-wiki/blob/master/General/SettingUpANewProject.md
Right click on the block and Accept
A new method will show in fourth from left pane

*** Adding Methods To Pass The Tests
In System Browser select Jacpac JacClass
On third from left pane select instance side
Right click ad select New protocol
add initialisation
Now clicking on initialization in third from left pane
will show bottom pane tan JacClass

I was able to use web examples by clicking bottom pane tab Inst. side method
pasting the method code
and right clicking and selecting Accept
that would add methods to fourth from left pane

package jacpac Jacclass
right click jump to test class
right click on JacClassTest option Run tests

** another introduction video
https://www.youtube.com/watch?v=WLoXXFxU8lw
11 years old!!!

*** intro
https://youtu.be/WLoXXFxU8lw?t=2

*** Pharo download
https://youtu.be/WLoXXFxU8lw?t=21

*** running it
https://youtu.be/WLoXXFxU8lw?t=40

Transcript
https://youtu.be/WLoXXFxU8lw?t=51

can be used as REPL

Hello World
https://youtu.be/WLoXXFxU8lw?t=81

Classes
https://youtu.be/WLoXXFxU8lw?t=119

Class categories, now they are packages
https://youtu.be/WLoXXFxU8lw?t=137

Class adding messages
https://youtu.be/WLoXXFxU8lw?t=161

adding method
https://youtu.be/WLoXXFxU8lw?t=171

saving method
https://youtu.be/WLoXXFxU8lw?t=181

calling the method in the Transcript
https://youtu.be/WLoXXFxU8lw?t=220

seeing the class in File Browser
https://youtu.be/WLoXXFxU8lw?t=260

the exclamation marks in the file
https://youtu.be/WLoXXFxU8lw?t=277

editing the file in external editor
https://youtu.be/WLoXXFxU8lw?t=297

bringing edited code back into the image
https://youtu.be/WLoXXFxU8lw?t=317
File entire file

closing the image without saving
https://youtu.be/WLoXXFxU8lw?t=353

upon restarting the image the last edits did not work
https://youtu.be/WLoXXFxU8lw?t=370

he runs again: File entire file
https://youtu.be/WLoXXFxU8lw?t=396

what's next
https://youtu.be/WLoXXFxU8lw?t=433
understand the image and the tools

* Other Smalltalks

** Cuis
https://github.com/nmingotti/The-Cuis-CookBook/wiki
https://cuis-smalltalk.github.io/TheCuisBook/
https://cuis.st/

** Squeak
pdf:/home/jacek/Documents/Manuals/Smalltalk/SBE-6.0.pdf#7

https://wiki.squeak.org/squeak/689
https://squeak.org/documentation/

https://books.pharo.org/
