* Readme

Here I will have my Elixir notes

https://elixir-lang.org/

** Installation on Linux with kerl

*** version managers

**** kerl

Kerl allows to install various versions of erlang. After that you can use decide
on a version of Elixir that will go with the installed erlang and if you fancy
you can add rebar3.

***** installing
untested
official
https://elixir-lang.org/install.html#unix-and-unix-like
ubuntu version
https://askubuntu.com/questions/1418015/elixir-installation-on-ubuntu


****** troubleshooting
https://github.com/kerl/kerl#installing-kerl

https://github.com/asdf-vm/asdf-erlang#ubuntu-2404-lts


kerl fails to build on the latest Linux Mint Beta


#+begin_example
=== Entering application ssh
gmake[3]: Entering directory '/home/jacek/.kerl/builds/27.0/otp_src_27.0/lib/ssh/src'
SED x86_64-pc-linux-gnu /home/jacek/.kerl/builds/27.0/otp_src_27.0
 GEN	/home/jacek/.kerl/builds/27.0/otp_src_27.0/lib/ssh/src/deps/ssh.d
/home/jacek/.kerl/builds/27.0/otp_src_27.0/lib/ssh/src/deps/ssh.d:1: *** empty variable name. Stop.
gmake[3]: Leaving directory '/home/jacek/.kerl/builds/27.0/otp_src_27.0/lib/ssh/src'
gmake[2]: *** [/home/jacek/.kerl/builds/27.0/otp_src_27.0/make/otp_subdir.mk:29: opt] Error 2
#+end_example

#+begin_example
  sudo apt-get -y install build-essential autoconf m4 libncurses5-dev libwxgtk3.2-dev libwxgtk-webview3.2-dev libgl1-mesa-dev libglu1-mesa-dev libpng-dev libssh-dev unixodbc-dev xsltproc fop libxml2-utils libncurses-dev openjdk-11-jdk

  sudo apt remove erlang elixir

  cd ~/bin
  curl -O https://raw.githubusercontent.com/kerl/kerl/master/kerl
  chmod +x ./kerl

  kerl upgrade
  kerl list releases
  kerl status
#+end_example

****** fixing kerl
https://github.com/kerl/kerl/issues/551

make sure that until the fix is provided
https://github.com/kerl/kerl/issues/551#issuecomment-2785557817
I do not have the following directories
#+begin_example
/home/jacek/.config/erlang/.erlang
/home/jacek/.erlang
#+end_example

tracing the build
#+begin_example
$ tail -f ~/.kerl/builds/25.0/otp_build_25.0.log
#+end_example

you can use the above example to see the output of kerl building erlang as in
the below example

****** installing kerl versions

#+begin_example
kerl update releases
kerl build 25.3.2.21 25
kerl install 25 ~/.erl/25

kerl build 27.3.4.1 27
kerl install 27 ~/.erl/27
#+end_example


****** stale warning
When you start the Terminal you may get the warning about stale environment
installed with older version of kerl.
#+begin_quote
this Erlang/OTP installation appears to be stale. Please consider reinstalling
#+end_quote

#+begin_example
  kerl_deactivate
  rm -rvf ~/.kerl
  # choose one of the releases
  kerl build 25.0 25.0
  kerl build 27.0 27.0
  # and install
  kerl install 25.0 ~/.erlang/25.0
  kerl list builds
#+end_example

****** install output
#+begin_example
You can activate this installation running the following command:
. /home/jacek/.erlang/25.0/activate
Later on, you can leave the installation typing:
kerl_deactivate
#+end_example

***** now install elixir

https://elixir-lang.org/install.html#precompiled-package

Elixir releases

I will try precompiled package for otp25

https://elixir-lang.org/install.html#precompiled-package

https://github.com/elixir-lang/elixir/releases/download/v1.17.0/elixir-otp-25.zip

https://github.com/elixir-lang/elixir/releases/download/v1.18.0/elixir-otp-25.zip

https://github.com/elixir-lang/elixir/releases/download/v1.17.3/elixir-otp-25.zip

So I downloaded the zip moved it to ~/.elixir
and extracted the folder

***** bashrc
file:~/.bashrc::1

add at the bottom of the file

#+begin_example
# selecting elixir and otp version
# export PATH="/home/jacek/.elixir/1.18.4/elixir-otp-25/bin:$PATH"
# . /home/jacek/.erl/25/activate
export PATH="/home/jacek/.elixir/1.18.4/elixir-otp-27/bin:$PATH"
. /home/jacek/.erl/27/activate
#+end_example

That allows me to run iex in the terminal.

**** rebar3 and elixir
https://meraj-gearhead.ca/adding-elixir-to-erlang-via-rebar3-2ad83476b627

https://github.com/marketplace/actions/setup-erlang-otp-with-optional-elixir-and-mix-and-or-rebar3

kerl recommended
https://github.com/erlang/rebar3?tab=readme-ov-file#getting-started

https://www.reddit.com/r/elixir/comments/15jzypg/adding_elixir_to_erlang_via_rebar3/

** Installing on Linux with asdf
pdf:/home/jacek/Documents/Manuals/Elixir/fromrubytoelixir.pdf#10

https://asdf-vm.com/guide/getting-started.html#install-asdf
https://github.com/asdf-vm/asdf/releases/download/v0.18.0/asdf-v0.18.0-linux-amd64.tar.gz

copy the compressed file to ~/bin/ and extract asdf binary, then remove the compressed file

list plugins
#+begin_example
asdf plugin list all | grep -P 'erlang|elixir'

  asdf plugin add elixir
  asdf plugin add erlang
  asdf plugin list
#+end_example

now create the folder
#+begin_example
  mkdir ./second
  touch ./second/.tool-versions
  # edit the versions to resemble
  # elixir 1.16.0-otp-26
  # erlang 26.2.1
  cd ./second/
  asdf install
#+end_example

.bashrc fragment
#+begin_example
export PATH="/home/jacek/.asdf/installs/elixir/1.16.0-otp-26/bin/":$PATH
. /home/jacek/.asdf/installs/erlang/26.2.1/activate
#+end_example


also consider setting environment script for per project settings
#+begin_example
#!/usr/bin/bash

echo "Setting environment"

export PATH="/home/jacek/.asdf/installs/elixir/1.16.0-otp-26/bin/":$PATH
. /home/jacek/.asdf/installs/erlang/26.2.1/activate
#+end_example

** Emacs
https://github.com/elixir-editors/emacs-elixir

https://github.com/tonini/alchemist.el

https://elixirforum.com/t/emacs-elixir-setup-configuration-wiki/19196

https://www.elixirwiki.com/wiki/Emacs_Configuration_Guide



** Books
more [[file:books/Readme.org::*Books][Books]]
