* Readme

Here I will have my Elixir notes

https://elixir-lang.org/

** Installation on Linux

*** version managers

**** kerl

Kerl allows to install various versions of erlang. After that you can use decide
on a version of Elixir that will go with the installed erlang and if you fancy
you can add rebar3.

***** installing

https://github.com/kerl/kerl#installing-kerl

#+begin_example
  sudo apt-get install build-essential git wget libssl-dev libreadline-dev libncurses5-dev zlib1g-dev m4 curl wx-common libwxgtk3.2-dev autoconf
  sudo apt remove erlang elixir

  cd ~/bin
  curl -O https://raw.githubusercontent.com/kerl/kerl/master/kerl
  chmod +x ./kerl

  kerl upgrade
  kerl list releases
  kerl status
#+end_example

tracing the build
#+begin_example
$ tail -f ~/.kerl/builds/25.0/otp_build_25.0.log
#+end_example

you can use the above example to see the output of kerl building erlang as in
the below example

#+begin_example
kerl update releases
kerl build 25.0 25.0
kerl install 25.0 ~/.erlang/25.0
#+end_example


****** stale warning
When you start the Terminal you may get the warning about stale environment
installed with older version of kerl.
#+begin_quote
this Erlang/OTP installation appears to be stale. Please consider reinstalling
#+end_quote

#+begin_example
  kerl_deactivate
  rm -rvf ~/.kerl
  kerl build 25.0 25.0
  kerl install 25.0 ~/.erlang/25.0
  kerl list builds
#+end_example

****** install output
#+begin_example
You can activate this installation running the following command:
. /home/jacek/.erlang/25.0/activate
Later on, you can leave the installation typing:
kerl_deactivate
#+end_example

***** now install elixir

I will try precompiled package for otp25

https://elixir-lang.org/install.html#precompiled-package

https://github.com/elixir-lang/elixir/releases/download/v1.17.0/elixir-otp-25.zip

So I downloaded the zip moved it to ~/.elixir
and extracted the folder

***** bashrc
file:~/.bashrc::1

add at the bottom of the file

#+begin_example
export PATH="/home/jacek/.elixir/elixir-otp-25/bin:$PATH"
. ~/.erlang/25.0/activate
#+end_example

That allows me to run iex in the terminal.

**** rebar3 and elixir
https://meraj-gearhead.ca/adding-elixir-to-erlang-via-rebar3-2ad83476b627

https://github.com/marketplace/actions/setup-erlang-otp-with-optional-elixir-and-mix-and-or-rebar3

kerl recommended
https://github.com/erlang/rebar3?tab=readme-ov-file#getting-started

https://www.reddit.com/r/elixir/comments/15jzypg/adding_elixir_to_erlang_via_rebar3/

** Emacs
https://github.com/elixir-editors/emacs-elixir

https://github.com/tonini/alchemist.el

https://elixirforum.com/t/emacs-elixir-setup-configuration-wiki/19196

https://www.elixirwiki.com/wiki/Emacs_Configuration_Guide



** Books
more [[file:books/Readme.org::*Books][Books]]
