* Readme

I need to explore Literate Lisp to a greater degree.

** literate-lisp
https://github.com/jingtaozf/literate-lisp

https://quickdocs.org/literate-lisp

*** example use with another system
asd
file:~/quicklisp/dists/quicklisp/software/s-graphviz-20201220-git/s-graphviz.asd::17
code use example
file:~/quicklisp/dists/quicklisp/software/s-graphviz-20201220-git/s-graphviz.org::42
https://raw.githubusercontent.com/jingtaozf/s-graphviz/master/s-graphviz.org
code formatted as Readme
https://github.com/jingtaozf/s-graphviz

** my first attempt
[[file:literat.org::*Literat][Literat]] is my first literate program.

** verdict

It is useless for real work. But it can be great as a teaching tool, especially
because it is good at showing the structure and hiding irrelevant details.

It is also an inspiration for thinking about a better tool. Such tool would have
elements of org-mode but done better. We need
+ code folding across comments
+ links to lines
+ links to structure elements
+ links to functions

Perhaps I could use occur instead of the links for jumping around the same file?
