* Roam How To


This folder is for folders with org-roam notes.

There should be a symbolic link called current that points to one of those
folders and is used by Emacs configuration.

#+begin_example
~/Documents/Roams$ ls -alh | grep current
lrwxrwxrwx  1 jacek jacek   14 Jan 17 18:35 current -> ./githubkasten
#+end_example

also there should be a switch_project script
#+begin_example
~/Documents/Roams$ ls -alh | grep switch
lrwxrwxrwx  1 jacek jacek   72 Apr 18  2025 switch_project -> /home/jacek/Programming/Pyrulis/Org-mode/org-roam-goodies/switch_project
#+end_example

** create a new project and switch to it
Make a new roam called ~diagram~ and switch project
#+begin_example
mkdir -p ./diagram/org-roam/daily
./switch_project ./diagram
#+end_example

Start Emacs and run M-x org-roam-dired.

In the folder that opens run M-x org-roam-db-sync.

Press C-x n f and enter the name of your first node. Press C-c C-c to confirm.

I can switch between folders using the switch_project script. The script creates
symbolic link from the folder to current. The current is defined in the Emacs
config as the part of the path loading to org-roam folder with the org-roam data.

** alternative to switch_project
The Emacs variable org-roam-my-folder
[[file:~/.emacs.d/personal/organised.el::(defvar org-roam-my-folder]]
allows me to redefine the location of the org-roam for the (separate) Emacs session and project without running
*switch-project*

Optionally create the folder, if it does not exist
Define the variable
#+begin_src emacs-lisp
  (let ((new-current "/tmp/scratch/org-roam"))
    (make-directory new-current :parents)
    (setq org-roam-my-folder new-current))
#+end_src

** recommended .gitignore
If we need to track the notes with git, we can use a .gitignore like that:
#+begin_example
# gitignore for org roam notes

# ignore database
org-roam/org-roam.db

# ignore accidentally exported html files
org-roam/*.html
#+end_example
