#!/home/jacek/.rbenv/shims/ruby

# require 'debug'

if ARGV.empty?
  puts 'Please provide the name of the folder which should become current'
elsif ARGV.size == 1
  folder = ARGV.first.strip
  folder = folder.chop if folder[-1, 1] == '/'

  puts "Switching the current Roam to #{folder}"

  # removing current
  `rm -vf ./current`

  # creating the folder
  foutput =
    if folder.start_with?('./')
      `mkdir -pv #{folder}/org-roam/daily`
    elsif folder.start_with?('/')
      `mkdir -pv #{folder}/org-roam/daily`
    else
      `mkdir -pv ./#{folder}/org-roam/daily`
    end
  puts foutput

  # linking the folder
  output = `ln -sv #{folder} ./current`

  puts output
elsif ARGV.size > 1
  puts 'Please provide only one argument, the name of the folder which should become current'
end
