(defun sentence ()    (append (noun-phrase) (verb-phrase)))
(defun noun-phrase () (append (article) (noun)))
(defun verb-phrase () (append (verb) (noun-phrase)))
(defun article ()     (one-of '(the a)))
(defun noun ()        (one-of '(man woman table)))
