* Notes
** Preface
*** Book outline
**** Part I
introduces the Common Lisp

**** Part II
covers four early A1 programs that all use rule-based pattern-matching
techniques.

**** Part III
detours from AI for a moment to present some general tools for more
efficient programming. The reader who masters the material in this part can be
considered an advanced Lisp programmer.

**** Part IV
covers some advanced AI programs.

**** Part V
includes material that is peripheral to AI but important for any serious
Lisp programmer.

*** Most Important For me
For the Professional Lisp Programmer: Read as much of the book as possible, and
refer back to it often. Part III and chapter 25 are particularly important.

*** A Note on Exercises
Sample exercises are provided throughout. Readers can test their level of under-
standing by faithfully doing the exercises. The exercises are graded on the scale [s],
[m], [h], [dl, which can be interpreted either as a level of difficulty or as an expected
time it will take to do the exercise:

| Code | Difficulty | Time to do |
|------+------------+------------|
| [s]  | Simple     | Seconds    |
| [m]  | Medium     | Minutes    |
| [h]  | Hard       | Hours      |
| [d]  | Difficult  | Days       |

The time to do the exercise is measured from the point that the concepts have
been well understood. If the reader is unclear on the underlying concepts, it might
take hours of review to understand a [m] problem. Answers to the exercises can be
found in a separate section at the end of each chapter.

** THE INDEX
PDF page 13

book page = pdf page - 24
** chapter 1
(last list n) last n items
*** the story of lambda
pdf page 44
Russell used ^ above a symbol for bound variables in his Principia Mathematica
Church initially moved ^ to the front of a symbol,
then switched to uppercase version of lambda Λ,
because it was confused with A he eventually switched to lowercase λ,
John McCarthy was student of Church, when he invented Lisp there was
no λ character on the keyboard, so we have lambda
*** sharp-quote
When a function appears at cdr part ot a list use of #' tells lisp evaluator
to treat is a a function instead of eveluating it using normal rules.
you could think of it as #'fn == (function fn)
*** lambda expressions can create functions at runtime
see section 3.16 about closures
*** 1.9 Lisp evaluation
**** expression
***** list
evaluated as:
****** special form expression
a list whose first element is operator
eg. (+ 1 2) 'john (quote john) #'fn (function fn)
+, ', quote, #', and function are operators
****** function application
is evaluated by first evaluating the arguments (the rest of list)
and then finding the functionvnamed by the first element of the list
and applying it to the evaluated arguments
eg. (+ a b)
here we first evaluate variables a & b, then we apply + to them
***** atom
****** symbol
evaluates to most recent value assigned to the variable named by symbol
****** non symbol
evaluates to itself, numbers, strings etc.
**** distinction between reading and evaluating
** chapter 2
*** 2.1
*** 2.2
trace on pdf page 61
(trace list of functions)
(trace)
visited functions listed
*** 2.3
**** defvar vs defparameter
The special forms defvar and defparameter both introduce special variables
and assign a value to them; the difference is that a
variable, like *grammar*, is routinely changed during the course of running
the program.
A parameter, like *simple-grammar*, on the other hand, will normally stay
constant. A change to a parameter is considered a change to the program,
not a change by the program.
**** assoc
CL-USER> (assoc 2 '((1 a) (2 b) (3 c)))
(2 B)

*** 2.4
**** two alternate approaches
***** most straightforward mapping of the problem to code
***** most natural notation available to solve the problem
then write interpreter for the notation

****** cons
******* involves extra step
******* more work for small problems
****** pros
******* usually easier to modify
******* work as much of the problem as possible in its own terms
******* minimise solution written directly in Lisp
*** 2.5
*** 2.6
**** rules and facts representation is easier for multiple purpose use
**** nested sentence structure
**** using STRAIGHTFORWARD FUNCTIONS we would be stuck
we would have to rewrite every function to generate additional structure
**** with new notation we can keep grammar and rewrite just generate function
to produce nested lists.
***** cons the category onto the front of each rewrite
***** do not append results
*** 2.7 Exercises
** chapter 3
*** 3.1
**** six programming maxims
***** be specific
for example when is more specific than if
***** use abstractions
You should not make mistake of invoking primitive functions directly

If you define a list of names:
(defvar *names*
 '((Robert E. Lee) ... ))
then you should also define functions to get at the components of each name.
To get Lee use (last-name (car *names*)) not (caddar *names*)

Use find or find if instead of loop, find is more specific, it is an abstraction.
It is more concise it's built in and it's easier to understand.
****** maxim conflicts
sometimes maxims are in conflict and experience will tell you which one to prefer
in such case remember rule 6: be consistent
***** be concise
***** use the provided tools
***** do not be obscure
***** be consistent
*** 3.2
**** defvar vs defparameter
defvar will be assigned initial value only if it does not have any value
defparameter will always assign supplied value
**** defstruct and default values
**** conditionals
it is considered poor style to use and & or for anything other than testing
a logical condition

When the main purpose is to return value rather than take action
cond & if (with explicit nil) are preferred over when & unless.

| action   | possibilities |
|----------+---------------|
| when     |             1 |
| if, cond |             2 |
| cond     |            3+ |

If there are several tests comparing an expression to constant then case is
appropriate
***** typecase
***** errors
****** ecase etypecase
****** ccase ctypecase
**** variables and places
**** repetition
***** some, every
loop over elements until condition
***** common idioms
***** recursion
***** macros
reading effort
****** try to copy established macros
****** backquote
*** 3.3
*** 3.4
*** 3.5
*** 3.6
*** 3.7
**** tree-equal
*** 3.8
*** 3.9
*** 3.10
*** 3.11
*** 3.12
*** 3.13
**** trace
**** describe, inspect, documentation, apropos
*** 3.14
**** error, cerror
**** timing
*** 3.15
*** 3.16 Closures
**** OOP
#+BEGIN_SRC lisp
(defun adder (c)
  "Return a function that adds c to its arguments"
  #'(lambda (x) (+ x c)))
#+END_SRC

> (mapcar (adder 3 ) ' ( 1 3 1 0 ) )
> (mapcar (adder 10) ' ( 1 3 1 0 ) )
each time we call edder with different c, it creates a different function

#+BEGIN_SRC lisp
(defun bank-account (balance)
           "Open a bank account starting with given balance."
           #'(lambda (action amount
                      (case action
                        (deposit (setf balance (+ balance amount)))
                        (withdraw (setf balance (- balance amount)))))))
#+END_SRC

now you can do OOP
> (setf my-account (bank-account 500.00)) => function
> (funcall my-account 'withdraw 75.00) => 425
*** 3.17
**** lexical variables
lexical variables can be accesses outside their scope if a function
returns lambda, as in example in section 3.16. we can still call lambda
that has access to the lexical variable
**** special variables
special variables != global variables
created by defvar defparameter
can be shadowed by local variables
can be bound both locally and globally

example of counter and report

this only works with special variables
(setf (symbol-value var) value)
(set var value)
**** exercise 3.6
*** 3.18
(multiple-value-bind (a b)
  (round 5.1)
  (format t "rounding values a ~a  b~a" a b))

return multiple values
(values 1 2 3)
*** 3.19
function alias in Lisp
(setf (symbol-function 'new-alias) #'old-function)
*** 3.20
*** 3.21 Exercises
**** formatting of a list of symbols as string
(format T "~@(~{~A~^ ~}.~)" '( this is a test))
***** explanation
~@( str ~) - tilde left-paren: case conversion
@ capitalizes

~{ iteration
here, based on the list length we create "~A ~A ~A"

~} iteration end

~^ - tilde circumflex: escape upward
terminates list processing, so we do not print last space before .

** chapter 4
*** 5 stages of developing AI program
**** 1 description
***** rough idea
***** prose
***** what we want to do
**** 2 specification
***** redescribing problem closer to a computable procedure
**** 3 implementation
**** 4 testing
**** 5 debugging & analysis
**** IMPORTANT remarks
***** fluid boundaries between stages
***** above order not important
****** TDD may have tests before implementation
***** problems at any stage may require redesign at previous stages
***** you can get away with partial description or specification
****** and then complete the specification based on better understanding
*** 4.1 Stage 1: Description
**** means ends analysis
***** example
| means                         | ends         |
|-------------------------------+--------------|
| need to go to the city centre | distance     |
| need to take bus              | ticket money |
| need to borrow                | from X       |
| need to ask X                 | phone call   |
| need to plan journey          | memory       |
| need to get on the bus        | walk         |
| need to got to go to the city | ride         |
**** theory of means ends
***** Aristotle
The nature of deliberation and its objects
***** the gist
the X does not deliberate whether he will achieve target Y
he assumes Y tries to attain it
he considers many ways to attain Y and considers the best
then he decides how and by what means
till he finds the first cause
if he comes on impossibility (eg. no money) then he gives up
otherwise he will try to do it
**** having theory write a program
***** understand more fully the Aristotle's principle
****** means ends analysis
******* describing what we want to happen
******* eliminate
******** difference between what I have and what I want
******* example - bus eliminates the difference
******** for going to town bus may be a solution
******** bus changes location
******* need
******** description
********* of allowable actions
********** can't bring city centre to my house
see next heading - closely related
********* and their preconditions and effects
******** definition of appropriateness

*** 4.2 Stage 2: Specification
**** at this point we have vague idea what we need to solve the problem
**** now we refine it

***** represent CURRENT STATE and GOAL STATE as sets of conditions
typical current state (hungry underweight) <- 2 conditions
typical goal (eaten overweight)

***** list allowable operators
****** constant for the problem duration
****** changeable to tackle new problems
***** operator -> a structure ((action) (preconditions) (effects))
****** limit possible effects
******* effects ADD or DELETE conditions of current state
***** complete problem described in terms
****** starting state
****** known operators
****** goal state
****** example
(gps '(hungry underweight) '(eaten overweight) list-of-operators )

Starting from '(hungry underweight) achieve '(eaten overweight)
using any combination of known operators and record actions taken

***** single goal condition
****** if already in the state DONE - trivially, no effort
****** otherwise find appropriate operator

***** operator is appropriate  if
****** on of the effects is to
add the goal in question
in other words if the goal is in the operators add-list
***** we can apply an operator if
****** achieve all preconditions
****** execute action and
******* update current state in terms of
******** add-list
******** delete-list

*** Stage 3: Implementation
**** specification complete enough
***** to lead directly to complete program
***** we already have variables, data types and functions


** last page
135
