* Readme

https://ocaml.org/docs/installing-ocaml

#+begin_example
  sudo apt install opam
  opam init -y
#+end_example

Run the command at the end of the output of the last command

run ~opam init~
and answer ~y~ to the question about bash profile, then restart terminal

** Install platform tools
#+begin_example
opam install dune ocaml-lsp-server odoc ocamlformat utop merlin base core core_bench
#+end_example


** check installation
https://ocaml.org/docs/installing-ocaml#check-installation

** .ocamlinit file
http://dev.realworldocaml.org/install.html

#+begin_example
#require "core.top";;
#require "ppx_jane";;
open Base;;
#+end_example

** tour
https://ocaml.org/docs/tour-of-ocaml

https://borretti.me/article/two-years-ocaml

http://rigaux.org/language-study/syntax-across-languages-per-language/OCaml.html

https://github.com/ocaml-multicore/ocaml-effects-tutorial

** editor
https://ocaml.org/docs/set-up-editor#vim-and-emacs

https://batsov.com/articles/2022/08/23/setting-up-emacs-for-ocaml-development/

** first program
https://ocaml.org/docs/your-first-program

#+begin_example
jacek@jacek-host:~$ cd /tmp
jacek@jacek-host:/tmp$ opam exec -- dune init proj hello
#+end_example

#+begin_example
jacek@jacek-host:/tmp$ cd hello
jacek@jacek-host:/tmp$ touch ./.ocamlformat
jacek@jacek-host:/tmp/hello$ opam exec -- dune exec hello
Hello, World!
#+end_example

** ocamlformat
https://ocaml.org/p/ocamlformat/latest/doc/getting_started.html

** search

*** docs
https://ocaml.org/docs/search?q=let

*** packages
https://ocaml.org/packages/search?q=base

** books
https://cs3110.github.io/textbook/chapters/intro/intro.html

english books
https://ocaml.org/books?language=english&difficulty=All&pricing=All

https://dev.realworldocaml.org/toc.html

MORE OCAML Algorithms, Methods & Diversions
pdf:/home/jacek/Documents/Manuals/OCaml/mlbook2.pdf#1

promising because of debugging
https://greenteapress.com/thinkocaml/thinkocaml.pdf

https://caml.inria.fr/pub/docs/oreilly-book/

** calling C
https://ocaml.org/docs/calling-c-libraries

** installing libraries

#+begin_example
opam install ounit2
#+end_example

** ocaml format problem

On Emacs ocamlformat fails silently if there is no .ocamlformat file in the
project. I need to find the locations that work, because the home folder did not.

is there a setting for that?
[[file:~/.emacs.d/elpa/ocamlformat-20230915.941/ocamlformat.el::(defcustom ocamlformat-enable 'enable]]

also M-x ocamlformat fixes the autocompletion on Tab

** OCaml basics

Simple Data Types pdf:/home/jacek/Documents/Manuals/OCaml/mlbook2.pdf#9
Names and Functions
Pattern Matching  pdf:/home/jacek/Documents/Manuals/OCaml/mlbook2.pdf#10
Lists
Exceptions
Partial Application
New Data Types
Basic Input / Output pdf:/home/jacek/Documents/Manuals/OCaml/mlbook2.pdf#11
Mutable State
Floating-point Numbers
The OCaml Standard Library
Simple Modules
Compiling Programs

** keywords

Keywords

The identifiers below are reserved as keywords, and cannot be employed otherwise:

#+begin_example
      and         as          assert      asr         begin       class
      constraint  do          done        downto      else        end
      exception   external    false       for         fun         function
      functor     if          in          include     inherit     initializer
      land        lazy        let         lor         lsl         lsr
      lxor        match       method      mod         module      mutable
      new         nonrec      object      of          open        or
      private     rec         sig         struct      then        to
      true        try         type        val         virtual     when
      while       with
#+end_example

The following character sequences are also keywords:

#+begin_example
    !=    #     &     &&    '     (     )     *     +     ,     -
    -.    ->    .     ..    .~    :     ::    :=    :>    ;     ;;
    <     <-    =     >     >]    >}    ?     [     [<    [>    [|
    ]     _     `     {     {<    |     |]    ||    }     ~
#+end_example

Note that the following identifiers are keywords of the now unmaintained Camlp4 system and should be avoided for backwards compatibility reasons.

#+begin_example
    parser    value    $     $$    $:    <:    <<    >>    ??
#+end_example
