* Readme

This is a fragment of the record of my struggles with PureScript. While I was
able to make some small changes like adding flags or POST in flame. The type
system is very annoying and simple things take hours or days where in a normal
language it would be 15 minutes job.

I reckon time spending ensuring there are no bugs would be shorter than the time
wasted trying to figure out why the code won't compile.

Recommended tooling
https://discourse.purescript.org/t/recommended-tooling-for-purescript-in-2022/3206

important document saying Flame may be better
https://github.com/laurentpayot/purescript-for-elm-developers#readme

** books
https://book.purescript.org/
https://book.purescript.org/index.html
https://book.purescript.org/chapter1.html#how-to-read-this-book

pdf:/home/jacek/Documents/Manuals/Purescript/fp-made-easier.pdf#3

** websites
https://www.purescript.org/

Discord
https://purescript.org/chat

Jordan Martinez Reference
https://jordanmartinez.github.io/purescript-jordans-reference-site/

Pursuit
https://pursuit.purescript.org/

Discourse, Purescript Forum
https://discourse.purescript.org/

Getting started
https://github.com/purescript/documentation/blob/master/guides/Getting-Started.md

Purescript Cookbook
https://github.com/JordanMartinez/purescript-cookbook/blob/master/README.md#recipes

Awesome Purescript
https://github.com/passy/awesome-purescript

** nvm, node and npm
https://nodejs.org/en/download/package-manager

** Emacs
https://github.com/purescript-emacs

https://github.com/purescript-emacs/purescript-mode

https://github.com/purescript-emacs/psc-ide-emacs

https://github.com/purescript-emacs/emacs-psci

** reading
[[file:reading-fp-made-easier.org::*Reading fp-made-easier][Reading fp-made-easier]]

** blogs

*** how I write purescript apps
https://dicioccio.fr/how-i-write-purescript-apps.html
https://dicioccio.fr/how-i-write-purescript-apps-part-ii.html
https://dicioccio.fr/how-i-write-purescript-apps-part-iii.html

** resources
https://github.com/purescript/documentation/tree/master#ecosystem

https://github.com/purescript/package-sets

** cook book
https://github.com/JordanMartinez/purescript-cookbook/blob/master/README.md#recipes

https://purescript-resources.readthedocs.io/en/latest/index.html

https://www.reddit.com/r/purescript/comments/1k90525/purescript_tutorials_focusing_on_ui/

** interesting alternatives
https://lean-lang.org/

https://agda.readthedocs.io/en/latest/index.html

https://proofassistants.stackexchange.com/

https://rescript-lang.org/
