DEFAULT: ./builddir/libgladian.so gladian.idr
	idris gladian.idr -o myExecFile

clean:
	rm -f myExecFile gladian.ibc


# reinstalling Idris

# $ cabal install cabal-uninstall
# $ cabal-uninstall idris
# $ cabal install -f ffi idris
